name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    env:
      NODE_ENV: test
    strategy:
      matrix:
        node: [18]
        os: [ubuntu-latest]
    name: Tests (Node.js v${{ matrix.node }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Clean install dependencies
        run: npm ci

      - name: Build app static files with Next.js export
        run: npm run build

      - name: Start DynamoDB and MongoDB containers
        run: npm run test:prepare

      - name: Run Jest tests
        run: npm run test:jest

      - name: Run Cypress component tests
        run: npm run test:component

      - name: Run Cypress E2E tests
        run: npm run test:e2e

      - name: Stop DynamoDB and MongoDB containers
        run: npm run test:cleanup
