name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    env:
      NODE_ENV: test
    strategy:
      matrix:
        node: [18]
        os: [ubuntu-latest]
    name: Tests (Node.js v${{ matrix.node }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Clean install dependencies
        run: npm ci

      - name: Start DynamoDB container on port 8000
        run: npm run dynamodb:start

      - name: Start MongoDB container on port 27107
        run: npm run mongodb:start

      - name: Run Jest tests
        run: npm run test:jest

      - name: Run Cypress component tests
        run: npm run test:component

      - name: Build APP Next.js export
        run: npm run app:build

      - name: Build API mock GraphQL lambdas
        run: npm run api:build

      - name: Start APP, API, wait for APP port and run Cypress E2E tests
        run: npm run test:e2e:start-test
