name: Node.js CI

on:
  push:
    branches: [feat/no-ref/todoapp]

jobs:
  unit-tests:
    strategy:
      matrix:
        node: [18]
        os: [ubuntu-latest]
    name: Node.js v${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Cache node modules
      #   id: cache-npm
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       **/node_modules
      #     key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('**/package-lock.json')}}

      - name: Use Node.js ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Clean install dependencies
        run: npm ci

      - name: Run Jest unit tests
        run: npm run test:unit

  component-tests:
    strategy:
      matrix:
        node: [18]
        os: [ubuntu-latest]
    name: Node.js v${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Clean install dependencies
        run: npm ci

      - name: Run component tests
        run: npm run test:component

  e2e-tests:
    strategy:
      matrix:
        node: [18]
        os: [ubuntu-latest]
    name: Node.js v${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.os }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Clean install dependencies
        run: npm ci

      # - name: Next.js build cache
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.npm
      #       ${{ github.workspace }}/.next/cache
      #     # Generate a new cache whenever packages or source files change.
      #     key: ${{ runner.os }}-${{ matrix.node }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
      #     # If source files changed but packages didn't, rebuild from a prior cache.
      #     restore-keys: |
      #       ${{ runner.os }}-${{ matrix.node }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Build Next.js project
        run: npm run build

      - name: Run E2E tests
        run: npm run test:e2e
